language: c++
sudo: required
dist: yakkety

notifications:
  irc:
    channels:
      - "irc.freenode.net#em.slashem.me"
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
script: "cd build; cmake . -DCMAKE_CXX_COMPILER=g++-6; make"
skip_join: true

matrix:
  include:
     - os: linux
     - os: osx
#    - compiler: clang
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.8
#          packages:
#            - clang-3.8
#            - libc++-dev
#      script: "cd build; cmake . -DCMAKE_CXX_COMPILER=clang++-3.8 -DCMAKE_CXX_FLAGS='-I../game/include -I../share/include -I../interface -std=c++14 -stdlib=libc++'; make"
