language: c++
sudo: required

notifications:
  irc:
    channels:
      - "irc.freenode.net#em.slashem.me"
    skip_join: true
#compiler: gcc

matrix:
  include:
     - os: osx
       before_install:
         - brew install gcc6 sdl2 sdl2_ttf
       compiler: gcc-6
       script: "cd build; cmake . -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6; make"
       osx_image: xcode8.0
     - os: osx
       before_install:
         - brew install sdl2 sdl2_ttf
       compiler: clang
       script: "cd build; cmake . -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++; make"
       osx_image: xcode8.0
     - os: linux
       before_install:
         - sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
         - sudo -E apt-get -yq update &>> ~/apt-get-update.log
         - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install g++-6 libsdl2-2.0 libsdl2-dev
       compiler: gcc
       dist: zesty
#       addons:
#         apt:
#           sources:
#             - ubuntu-toolchain-r-test
#           packages:
#             - g++-6
       script: "cd build; cmake . -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6; make"
     - os: linux
       before_install:
         - curl -sSL "http://llvm.org/apt/llvm-snapshot.gpg.key" | sudo -E apt-key add -
         - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.8 main" | sudo tee -a /etc/apt/sources.list > /dev/null
         - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install clang-3.8 llvm-3.8-dev libc++-dev libsdl2-2.0 libsdl2-dev
       compiler: clang
       dist: zesty
#       addons:
#         apt:
#           sources:
#             - llvm-toolchain-precise-3.8
#           packages:
#             - clang-3.8
#             - llvm-3.8-dev
#             - libc++-dev
       script: "cd build; cmake . -DCMAKE_C_COMPILER=clang-3.8 -DCMAKE_CXX_COMPILER=clang++-3.8 -Dcxxflags=\"-stdlib=libc++\"; make"
