language: c++
sudo: required
dist: yakkety
script: "cd build; cmake .; make"
compiler:
  - gcc
  - clang
notifications:
  irc:
    channels:
      - "irc.freenode.net#em.slashem.me"
    skip_join: true
