language: c++
sudo: required

notifications:
  irc:
    channels:
      - "irc.freenode.net#em.slashem.me"
    skip_join: true
#compiler: gcc

matrix:
  include:
     - os: osx
       compiler: gcc-4.9
       script: "cd build; cmake . -DCMAKE_CXX_COMPILER=g++-4.9; make"
       osx_image: xcode8.0
     - os: osx
       compiler: clang
       script: "cd build; cmake . -DCMAKE_CXX_COMPILER=clang++; make"
       osx_image: xcode8.0
     - os: linux
       addons:
         dist: zesty
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
             - g++-6
       script: "cd build; cmake . -DCMAKE_CXX_COMPILER=g++-6; make"
     - os: linux
       addons:
         dist: zesty
         apt:
           sources:
             - ubuntu-toolchain-r-test
             - llvm-toolchain-precise-3.8
           packages:
             - clang-3.8
       script: "cd build; cmake . -DCMAKE_CXX_COMPILER=clang++-3.8; make"
#    - compiler: clang
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.8
#          packages:
#            - clang-3.8
#            - libc++-dev
#      script: "cd build; cmake . -DCMAKE_CXX_COMPILER=clang++-3.8 -DCMAKE_CXX_FLAGS='-I../game/include -I../share/include -I../interface -std=c++14 -stdlib=libc++'; make"
